server:
  port: ${PORT:8090}
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:
  scan:
    base-packages: io.kubesphere.services.employee
  protocols:
    dubbo:
      name: dubbo
    rest:
      name: rest
      port: ${PORT:8090}
      server: tomcat
  registry:
    #   The Spring Cloud Dubbo's registry extension
    address: spring-cloud://localhost