server:
  port: ${PORT:8060}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:8761/eureka/}

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    department:
      path: /department/**
      serviceId: department-service
    employee:
      path: /employee/**
      serviceId: employee-service
    organization:
      path: /organization/**
      serviceId: organization-service