apiVersion: v1
kind: Service
metadata:
  name: organization-sample
  namespace: kubesphere-springcloud-sample
  labels:
    app: organization-sample
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: organization-sample
  selector:
    app: organization-sample
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: organization-sample
  name: organization-sample
  namespace: kubesphere-springcloud-sample
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: organization-sample
  template:
    metadata:
      labels:
        app: organization-sample
    spec:
      containers:
        - image: runzexia/organization-sample:latest
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          env:
            - name: PORT
              value: "8080"
            - name: CONFIG_SERVER
              value: "http://config-sample:8080"
            - name: EUREKA_SERVER
              value: "http://eureka-sample-0.eureka-sample:8761/eureka/,http://eureka-sample-1.eureka-sample:8761/eureka/,http://eureka-sample-2.eureka-sample:8761/eureka/"
          imagePullPolicy: Always
          name: organization-sample
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30